#===========================================================================
#
# PyRun bootloader for #$pyrun (based on Python #$version)
#
#---------------------------------------------------------------------------
#
# This template is used by makepyrun.py to build the bootloader
# script for PyRun.
#
# It uses these placeholders (all prefixed with "#$", which are filled
# in with the appropriate data by makepyrun.py:
#
# * pyrun    - name of the pyrun executable
# * version  - version of the pyrun executable (the supported Python version)
# * release  - pyrun release version
# * imports  - imports generated by makepyrun.py, so that freeze.py
#              can find all needed modules to include in the
#              pyrun executable
#
# Compatible to Python 2.7 and 3.4+

# Copyright information
COPYRIGHT = """\

    Copyright (c) 1997-2000, IKDS Marc-Andre Lemburg; mailto:mal@lemburg.com
    Copyright (c) 2000-2024, eGenix.com Software GmbH; mailto:info@egenix.com

                            All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

### Imports

import sys
import pyrun_main

### Entry point

if __name__ == '__main__':
    pyrun_main.pyrun_main()

# Should not get here...
sys.exit(0)

### freeze.py Hooks

# This is unreachable code used as hook for freeze.py to include
# the standard Python library.
#$imports

# PyRun specific modules to include
import pyrun_config
import pyrun_extras
